### ISSUE TITLE
Why alphabetical?

### ISSUE THREAD

**Issue by corysimmons** [suitcss/suit#127]
https://github.com/suitcss/suit/blob/283397f5a09c3318c53cfa56e1ad75198ce1b513/doc/STYLE.md#declaration-order

Not trying to pick a fight. Just curious if it's something more than being able to visually find what you're looking for. I've always done it with things that I feel affect the layout first and just prettying tweaks next as this is my natural order of designing something (cutting the big chunks of hair off before styling it).

**Comment by jeddy3** [comment]
> being able to visually find what you're looking for

I think that's why.

Everyone already knows the alphabet. In contrast, if the declarations were ordered by some other criteria, each member of the team would need to learn (and remember) a set of rules.

As an example, say there's a new developer tasked with maintaining some CSS and is trying to fix a bug with the stacking context. The developer could quickly determine which rule-sets have a `z-index` declaration by looking towards the bottom of each declaration block. This requires little thought.

In contrast, if the declarations were ordered by some other criteria, the developer would first need to establish—likely by referring to some documentation which is most probably stored externally from the file he or she is currently working on—where to look for a `z-index` declaration within each block.

I think it also removes the need for a team to take the time out to establish and rationalise the criteria i.e. what groups are there, and what properties belong to each group? 

Personally, I've found it quite beneficial when working within teams (especially with new starters). Your mileage, of course, my vary depending on the needs of your project and team.

I'm also curious to hear if there are more reason for it though :)

**Comment by simonsmith** [comment]
Basically what @jeddy3 said.

If you group by things like layout then you still need to decide what order related declarations are placed in. For example `font-weight: bold` and `font-size: 24px` are all related to typography, but what decides their order?

Using alphabetical is simple and most editors can help you with it, for example using `:sort` in Vim. Of course with Stylelint you're free to enforce [your own choice](http://stylelint.io/?/src/rules/rule-properties-order/README.md) too.

**Comment by corysimmons** [comment]
Why not order by group type then order alphabetically?

**Comment by jeddy3** [comment]
> Why not order by group type then order alphabetically?

I still think for the reason I gave above i.e. a new developer would need to learn (and have to remember) what the groups are, and the order that the groups come in. Even if the declarations are ordered alphabetically within each group.

It adds an obstacle to contributing. 

So I think your choice of property ordering is dependent on the project team e.g. for an internal team with a low turn over grouping probably makes sense, but if the team has a high turn over or if you accept contributions from a wide net (e.g. a open source project) you might want to reduce the barrier to contributing and go with alphabetical.

This might be the usual case of different solutions for different needs :-)

**Comment by giuseppeg** [comment]
If you use `suitcss-preprocessor` you can write your rules in any order and use the [`beforeLint`](https://github.com/suitcss/preprocessor#beforelint) hook with `postcss-sort` to sort them before the styles get passed through `stylelint`.

That or simply tweak the `stylelint` configuration.

**Comment by corysimmons** [comment]
Thanks guys.
