### ISSUE TITLE
Suit and Twitter bootstrap

### ISSUE THREAD

**Issue by xfg** [suitcss/suit#97]
What do if I want use suit methodology and twitter bootstrap framework in one application?

**Comment by simonsmith** [comment]
It depends which parts you want to mix. Obviously you don't need two grid frameworks.

I worked on a codebase that was Bootstrap, and we migrated it to SUIT. To do that we treated bootstrap classes as utilities. So for example:

``` html
<ul class="Component list-group">
  <li class="Component-item list-group-item"></li>
</ul>
```

It gets trickier when you mix components that are closely linked, like buttons. Overall I would recommend one or the other but I've not missed Bootstrap since using SUIT exclusively.

**Comment by xfg** [comment]
I want use any of parts twitter bootstrap and I want use SUIT only for my css classes.

**Comment by simonsmith** [comment]
See my previous comment for combining the two

**Comment by xfg** [comment]
Thanks.

**Comment by necolas** [comment]
You might have issues with Bootstrap styling things you didn't want styled, but I think Simon's suggestion is sensible.
